### ISSUE TITLE
Keine Kurse und Dateien gefunden

### ISSUE THREAD

**Issue by freedome97** [cold-soda-jay/iliaD#3]
Ich habe iliaD init ausgeführt, die Parameter eingetragen und iliaD course aufgerufen.
Das Resultat der Kurse entspricht der Startseite (Magazin), jedoch nicht dem Dashboard.

![image](https://user-images.githubusercontent.com/50106400/198557933-e397c2fc-a438-4395-9bd9-da499eb76934.png)

Edit: Ich habe dann manuell die course.json angepasst, um auf die Kurse zu zeigen. iliaD synch lädt allerdings keine Dateien runter.

**Comment by cold-soda-jay** [comment]
Es tut mir leid. Gerade habe ich schon absolviert und habe keine Zugang mehr. Deshalb ist für mich nicht möglich diese Fehler zu beheben... 
Das sieht allerdings wie eine Änderung des UI von ilias. Du kannst versuchen fork und weiterentwickln. Ich helfe immer gerne :-)
